using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using BitcoinTrader.Library.Business;

namespace CommandCenter
{
    public partial class ScoreCardView : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            string algo = Request.QueryString["aname"];

            ScoreCard card1 = new ScoreCard((decimal)1000.00);
            card1.Load(algo, GroupBy.halfhour, 1325376000);
            ScoreCard card2 = new ScoreCard((decimal)1000.00);
            card2.Load(algo, GroupBy.hour, 1325376000);
            ScoreCard card3 = new ScoreCard((decimal)1000.00);
            card3.Load(algo, GroupBy.doublehour, 1325376000);
            ScoreCard card4 = new ScoreCard((decimal)1000.00);
            card4.Load(algo, GroupBy.day, 1325376000);
            ScoreCard card5 = new ScoreCard((decimal)1000.00);
            card5.Load(algo, GroupBy.doubleday, 1325376000);
            ScoreCard card6 = new ScoreCard((decimal)1000.00);
            card6.Load(algo, GroupBy.week, 1325376000);

            lblTNPMin.Text = String.Format("${0}", card1.NetProfit == decimal.MaxValue ? "infinity" : string.Format("{0:N4}",card1.NetProfit));
            lblTNPHour.Text = String.Format("${0:N4}", card2.NetProfit);
            lblTNP2Hour.Text = String.Format("${0:N4}", card3.NetProfit);
            lblTNPDay.Text = String.Format("${0:N4}", card4.NetProfit);
            lblTNP2Day.Text = String.Format("${0:N4}", card5.NetProfit);
            lblTNPWeek.Text = String.Format("${0:N4}", card6.NetProfit);
            lblNumberOfTradesMin.Text = String.Format("{0}", card1.NumberOfTrades);
            lblNumberOfTradesHour.Text = String.Format("{0}", card2.NumberOfTrades);
            lblNumberOfTrades2Hour.Text = String.Format("{0}", card3.NumberOfTrades);
            lblNumberOfTradesDay.Text = String.Format("{0}", card4.NumberOfTrades);
            lblNumberOfTrades2Day.Text = String.Format("{0}", card5.NumberOfTrades);
            lblNumberOfTradesWeek.Text = String.Format("{0}", card6.NumberOfTrades);
            lblTotalAverageProfitPerTradeMin.Text = String.Format("${0:N4}", card1.AverageProfitPerTrade);
            lblTotalAverageProfitPerTradeHour.Text = String.Format("${0:N4}", card2.AverageProfitPerTrade);
            lblTotalAverageProfitPerTrade2Hour.Text = String.Format("${0:N4}", card3.AverageProfitPerTrade);
            lblTotalAverageProfitPerTradeDay.Text = String.Format("${0:N4}", card4.AverageProfitPerTrade);
            lblTotalAverageProfitPerTrade2Day.Text = String.Format("${0:N4}", card5.AverageProfitPerTrade);
            lblTotalAverageProfitPerTradeWeek.Text = String.Format("${0:N4}", card6.AverageProfitPerTrade);
            lblAveragePrcntProfitPerTradeMin.Text = String.Format("{0:N4}%", card1.AverageProfitPercentPerTrade);
            lblAveragePrcntProfitPerTradeHour.Text = String.Format("{0:N4}%", card2.AverageProfitPercentPerTrade);
            lblAveragePrcntProfitPerTrade2Hour.Text = String.Format("{0:N4}%", card3.AverageProfitPercentPerTrade);
            lblAveragePrcntProfitPerTradeDay.Text = String.Format("{0:N4}%", card4.AverageProfitPercentPerTrade);
            lblAveragePrcntProfitPerTrade2Day.Text = String.Format("{0:N4}%", card5.AverageProfitPercentPerTrade);
            lblAveragePrcntProfitPerTradeWeek.Text = String.Format("{0:N4}%", card6.AverageProfitPercentPerTrade);
            lblProfTradesMin.Text = String.Format("{0}", card1.ProfitableTrades);
            lblProfTradesHour.Text = String.Format("{0}", card2.ProfitableTrades);
            lblProfTrades2Hour.Text = String.Format("{0}", card3.ProfitableTrades);
            lblProfTradesDay.Text = String.Format("{0}", card4.ProfitableTrades);
            lblProfTrades2Day.Text = String.Format("{0}", card5.ProfitableTrades);
            lblProfTradesWeek.Text = String.Format("{0}", card6.ProfitableTrades);
            lblWinRateMin.Text = String.Format("{0:N4}", card1.WinRate);
            lblWinRateHour.Text = String.Format("{0:N4}%", card2.WinRate);
            lblWinRate2Hour.Text = String.Format("{0:N4}%", card3.WinRate);
            lblWinRateDay.Text = String.Format("{0:N4}%", card4.WinRate);
            lblWinRate2Day.Text = String.Format("{0:N4}%", card5.WinRate);
            lblWinRateWeek.Text = String.Format("{0:N4}%", card6.WinRate);
            lblTotalGrossProfitMin.Text = String.Format("${0:N4}", card1.TotalGrossProfit);
            lblTotalGrossProfitHour.Text = String.Format("${0:N4}", card2.TotalGrossProfit);
            lblTotalGrossProfit2Hour.Text = String.Format("${0:N4}", card3.TotalGrossProfit);
            lblTotalGrossProfitDay.Text = String.Format("${0:N4}", card4.TotalGrossProfit);
            lblTotalGrossProfit2Day.Text = String.Format("${0:N4}", card5.TotalGrossProfit);
            lblTotalGrossProfitWeek.Text = String.Format("${0:N4}", card6.TotalGrossProfit);
            lblAverageProfitPerTradeMin.Text = String.Format("${0:N4}", card1.ProfitableTradesAverageProfitPerTrade);
            lblAverageProfitPerTradeHour.Text = String.Format("${0:N4}", card2.ProfitableTradesAverageProfitPerTrade);
            lblAverageProfitPerTrade2Hour.Text = String.Format("${0:N4}", card3.ProfitableTradesAverageProfitPerTrade);
            lblAverageProfitPerTradeDay.Text = String.Format("${0:N4}", card4.ProfitableTradesAverageProfitPerTrade);
            lblAverageProfitPerTrade2Day.Text = String.Format("${0:N4}", card5.ProfitableTradesAverageProfitPerTrade);
            lblAverageProfitPerTradeWeek.Text = String.Format("${0:N4}", card6.ProfitableTradesAverageProfitPerTrade);
            lblAverageProfitPrcntPerTradeMin.Text = String.Format("{0:N4}%", card1.AverageProfitPrcntPerTrade);
            lblAverageProfitPrcntPerTradeHour.Text = String.Format("{0:N4}%", card2.AverageProfitPrcntPerTrade);
            lblAverageProfitPrcntPerTrade2Hour.Text = String.Format("{0:N4}%", card3.AverageProfitPrcntPerTrade);
            lblAverageProfitPrcntPerTradeDay.Text = String.Format("{0:N4}%", card4.AverageProfitPrcntPerTrade);
            lblAverageProfitPrcntPerTrade2Day.Text = String.Format("{0:N4}%", card5.AverageProfitPrcntPerTrade);
            lblAverageProfitPrcntPerTradeWeek.Text = String.Format("{0:N4}%", card6.AverageProfitPrcntPerTrade);
            lblMaxConsecutiveWinnersMin.Text = String.Format("{0:N4}", card1.MaxConsecutiveWinners);
            lblMaxConsecutiveWinnersHour.Text = String.Format("{0:N4}", card2.MaxConsecutiveWinners);
            lblMaxConsecutiveWinners2Hour.Text = String.Format("{0:N4}", card3.MaxConsecutiveWinners);
            lblMaxConsecutiveWinnersDay.Text = String.Format("{0:N4}", card4.MaxConsecutiveWinners);
            lblMaxConsecutiveWinners2Day.Text = String.Format("{0:N4}", card5.MaxConsecutiveWinners);
            lblMaxConsecutiveWinnersWeek.Text = String.Format("{0:N4}", card6.MaxConsecutiveWinners);
            lblUnprofitableTradesMin.Text = String.Format("{0:N4}", card1.UnprofitableTrades);
            lblUnprofitableTradesHour.Text = String.Format("{0}", card2.UnprofitableTrades);
            lblUnprofitableTrades2Hour.Text = String.Format("{0}", card3.UnprofitableTrades);
            lblUnprofitableTradesDay.Text = String.Format("{0}", card4.UnprofitableTrades);
            lblUnprofitableTrades2Day.Text = String.Format("{0}", card5.UnprofitableTrades);
            lblUnprofitableTradesWeek.Text = String.Format("{0}", card6.UnprofitableTrades);
            lblLossRateMin.Text = String.Format("{0:N4}", card1.LossRate);
            lblLossRateHour.Text = String.Format("{0:N4}%", card2.LossRate);
            lblLossRate2Hour.Text = String.Format("{0:N4}%", card3.LossRate);
            lblLossRateDay.Text = String.Format("{0:N4}%", card4.LossRate);
            lblLossRate2Day.Text = String.Format("{0:N4}%", card5.LossRate);
            lblLossRateWeek.Text = String.Format("{0:N4}%", card6.LossRate);
            lblTotalGrossLossMin.Text = String.Format("{0:N4}", card1.TotalGrossLoss);
            lblTotalGrossLossHour.Text = String.Format("${0:N4}", card2.TotalGrossLoss);
            lblTotalGrossLoss2Hour.Text = String.Format("${0:N4}", card3.TotalGrossLoss);
            lblTotalGrossLossDay.Text = String.Format("${0:N4}", card4.TotalGrossLoss);
            lblTotalGrossLoss2Day.Text = String.Format("${0:N4}", card5.TotalGrossLoss);
            lblTotalGrossLossWeek.Text = String.Format("${0:N4}", card6.TotalGrossLoss);
            lblAverageLossPerTradeMin.Text = String.Format("{0:N4}", card1.AverageLossPerTrade);
            lblAverageLossPerTradeHour.Text = String.Format("${0:N4}", card2.AverageLossPerTrade);
            lblAverageLossPerTrade2Hour.Text = String.Format("${0:N4}", card3.AverageLossPerTrade);
            lblAverageLossPerTradeDay.Text = String.Format("${0:N4}", card4.AverageLossPerTrade);
            lblAverageLossPerTrade2Day.Text = String.Format("${0:N4}", card5.AverageLossPerTrade);
            lblAverageLossPerTradeWeek.Text = String.Format("${0:N4}", card6.AverageLossPerTrade);
            lblAverageLossPrcntPerTradeMin.Text = String.Format("{0:N4}%", card1.AverageLossPercentPerTrade);
            lblAverageLossPrcntPerTradeHour.Text = String.Format("{0:N4}%", card2.AverageLossPercentPerTrade);
            lblAverageLossPrcntPerTrade2Hour.Text = String.Format("{0:N4}%", card3.AverageLossPercentPerTrade);
            lblAverageLossPrcntPerTradeDay.Text = String.Format("{0:N4}%", card4.AverageLossPercentPerTrade);
            lblAverageLossPrcntPerTrade2Day.Text = String.Format("{0:N4}%", card5.AverageLossPercentPerTrade);
            lblAverageLossPrcntPerTradeWeek.Text = String.Format("{0:N4}%", card6.AverageLossPercentPerTrade);
            lblMaxConsecutiveLossesMin.Text = String.Format("{0:N4}", card1.MaxConsecutiveLosses);
            lblMaxConsecutiveLossesHour.Text = String.Format("{0:N4}", card2.MaxConsecutiveLosses);
            lblMaxConsecutiveLosses2Hour.Text = String.Format("{0:N4}", card3.MaxConsecutiveLosses);
            lblMaxConsecutiveLossesDay.Text = String.Format("{0:N4}", card4.MaxConsecutiveLosses);
            lblMaxConsecutiveLosses2Day.Text = String.Format("{0:N4}", card5.MaxConsecutiveLosses);
            lblMaxConsecutiveLossesWeek.Text = String.Format("{0:N4}", card6.MaxConsecutiveLosses);
            lblMaxDrawDownMin.Text = String.Format("{0:N4}", card1.MaxDrawdown);
            lblMaxDrawDownHour.Text = String.Format("${0:N4}", card2.MaxDrawdown);
            lblMaxDrawDown2Hour.Text = String.Format("${0:N4}", card3.MaxDrawdown);
            lblMaxDrawDownDay.Text = String.Format("${0:N4}", card4.MaxDrawdown);
            lblMaxDrawDown2Day.Text = String.Format("${0:N4}", card5.MaxDrawdown);
            lblMaxDrawDownWeek.Text = String.Format("${0:N4}", card6.MaxDrawdown);
            lblMaximumDrawdownDateMin.Text = String.Format("{0}", card1.MaxDrawdownDate);
            lblMaximumDrawdownDateHour.Text = String.Format("{0}", card2.MaxDrawdownDate);
            lblMaximumDrawdownDate2Hour.Text = String.Format("{0}", card3.MaxDrawdownDate);
            lblMaximumDrawdownDateDay.Text = String.Format("{0}", card4.MaxDrawdownDate);
            lblMaximumDrawdownDate2Day.Text = String.Format("{0}", card5.MaxDrawdownDate);
            lblMaximumDrawdownDateWeek.Text = String.Format("{0}", card6.MaxDrawdownDate);
        }
    }
}